"""Plugin-wide constants. Versioned custom_id prefix lives here."""

PLUGIN_ID = "dnd_campaign_manager"
PLUGIN_VERSION = "1.0.0"

CUSTOM_ID_PREFIX = "dnd_v1"

COLOR_PRIMARY = 0x7C3AED
COLOR_SUCCESS = 0x22C55E
COLOR_WARNING = 0xF59E0B
COLOR_DANGER = 0xEF4444
COLOR_MUTED = 0x6B7280
COLOR_INFO = 0x3B82F6

EMBED_TITLE_MAX = 256
EMBED_DESC_MAX = 4096
EMBED_FIELD_VALUE_MAX = 1024
EMBED_FOOTER_MAX = 2048
MODAL_TITLE_MAX = 45
MODAL_FIELDS_MAX = 5
SELECT_OPTIONS_MAX = 25
BUTTON_LABEL_MAX = 80
CUSTOM_ID_MAX = 100

DEFAULT_REMINDER_OFFSETS_MINUTES = [1440, 120, 15]
DEFAULT_SESSION_DURATION_MINUTES = 240
SERIES_MATERIALIZE_AHEAD = 4
SERIES_EXTEND_THRESHOLD = 2
RECAP_BUTTON_DELAY_MINUTES = 30

REMINDER_POLL_INTERVAL_SECONDS = 60
SERIES_EXTEND_TICK_KEY = "last_series_extend_tick_utc"
SERIES_EXTEND_TICK_MIN_INTERVAL_SECONDS = 3600

SCHEMA_VERSION_KEY = "schema_version"

INTERACTION_TYPE_COMMAND = 2
INTERACTION_TYPE_COMPONENT = 3
INTERACTION_TYPE_MODAL_SUBMIT = 5

DISCORD_PERMISSION_ADMINISTRATOR = 0x8
